name: azure-backend

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

permissions:
  id-token: write  # Required for Workload Identity Federation
  contents: read   # Necessary for actions/checkout and other read operations

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4
        with:
          repository: aitdevops/backend
          token: ${{ secrets.GH_TOKEN }}
          path: backend

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker CLI
        run: |
          az acr login --name aitdevops  # Log in to Azure Container Registry

      - name: Build and push approval-service image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-approval  # Generate a unique image tag based on the current date and time
          docker build -t aitdevops.azurecr.io/approval-service:$IMAGE_TAG -f backend/approval-service/Dockerfile backend/approval-service
          docker push aitdevops.azurecr.io/approval-service:$IMAGE_TAG

      - name: Build and push auth-service image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-auth  # Generate a unique image tag based on the current date and time
          docker build -t aitdevops.azurecr.io/auth-service:$IMAGE_TAG -f backend/auth-service/Dockerfile backend/auth-service
          docker push aitdevops.azurecr.io/auth-service:$IMAGE_TAG

      - name: Build and push user-service image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-user  # Generate a unique image tag based on the current date and time
          docker build -t aitdevops.azurecr.io/user-service:$IMAGE_TAG -f backend/user-service/Dockerfile backend/user-service
          docker push aitdevops.azurecr.io/user-service:$IMAGE_TAG

      - name: Configure git
        run: |
          git config --global user.email "rajeevkoppisetti21@gmail.com"
          git config --global user.name "aitdevops"

      - name: Clone ArgoCD repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git
          cd argocd
          git checkout main

      - name: Update Kubernetes manifests for approval-service
        run: |
          cd argocd
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-approval
          sed -i 's|image:.*|image: "aitdevops.azurecr.io/approval-service:'$IMAGE_TAG'"|g' azure/backend/approval-service/deployment.yaml
          git add azure/backend/approval-service/deployment.yaml
          git commit -m "Update approval-service image to $IMAGE_TAG"

      - name: Update Kubernetes manifests for auth-service
        run: |
          cd argocd
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-auth
          sed -i 's|image:.*|image: "aitdevops.azurecr.io/auth-service:'$IMAGE_TAG'"|g' azure/backend/auth-service/deployment.yaml
          git add azure/backend/auth-service/deployment.yaml
          git commit -m "Update auth-service image to $IMAGE_TAG"

      - name: Update Kubernetes manifests for user-service
        run: |
          cd argocd
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-user
          sed -i 's|image:.*|image: "aitdevops.azurecr.io/user-service:'$IMAGE_TAG'"|g' azure/backend/user-service/deployment.yaml
          git add azure/backend/user-service/deployment.yaml
          git commit -m "Update user-service image to $IMAGE_TAG"

      - name: Push changes
        run: |
          cd argocd
          git push https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git main
