name: Build and Push backend Image, Update Helm Values

on:
  repository_dispatch:
    types: [backend_push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2
        with:
          repository: aitdevops/backend
          token: ${{ secrets.GH_TOKEN }}
          path: backend

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push backend image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/backend:$IMAGE_TAG -f backend/backend/Dockerfile ./backend/backend
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/backend:$IMAGE_TAG

      - name: Configure git
        run: |
          git config --global user.email "rajeevkoppisetti21@gmail.com"
          git config --global user.name "aitdevops"

      - name: Clone argocd repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git
          cd argocd
          git checkout main

      - name: Update Helm values
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          cd argocd
          sed -i 's|tag:.*|tag: '$IMAGE_TAG'|g' charts/aitdevops-backend/values.yaml
          git add charts/aitdevops-backend/values.yaml
          git commit -m "Update backend image to $IMAGE_TAG"

      - name: Push changes
        run: |
          cd argocd
          git push https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git main
