name: Build and Push Backend Images, Update Helm Values

on:
  repository_dispatch:
    types: [backend_push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2
        with:
          repository: aitdevops/backend
          token: ${{ secrets.GH_TOKEN }}
          path: backend

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push approval-service image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-approval
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/approval-service:$IMAGE_TAG -f backend/approval-service/Dockerfile backend/approval-service
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/approval-service:$IMAGE_TAG

      - name: Build and push auth-service image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-auth
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/auth-service:$IMAGE_TAG -f backend/auth-service/Dockerfile backend/auth-service
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/auth-service:$IMAGE_TAG

      - name: Build and push user-service image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-user
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/user-service:$IMAGE_TAG -f backend/user-service/Dockerfile backend/user-service
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/user-service:$IMAGE_TAG

      - name: Configure git
        run: |
          git config --global user.email "rajeevkoppisetti21@gmail.com"
          git config --global user.name "aitdevops"

      - name: Clone argocd repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git
          cd argocd
          git checkout main

      - name: Update Helm values for approval-service
        run: |
          sed -i 's|approvalServiceTag:.*|approvalServiceTag: '${GITHUB_SHA::7}-approval'|g' charts/aitdevops-backend/values.yaml
          git add charts/aitdevops-backend/values.yaml
          git commit -m "Update approval-service image to ${GITHUB_SHA::7}-approval"

      - name: Update Helm values for auth-service
        run: |
          sed -i 's|authServiceTag:.*|authServiceTag: '${GITHUB_SHA::7}-auth'|g' charts/aitdevops-backend/values.yaml
          git add charts/aitdevops-backend/values.yaml
          git commit -m "Update auth-service image to ${GITHUB_SHA::7}-auth"

      - name: Update Helm values for user-service
        run: |
          sed -i 's|userServiceTag:.*|userServiceTag: '${GITHUB_SHA::7}-user'|g' charts/aitdevops-backend/values.yaml
          git add charts/aitdevops-backend/values.yaml
          git commit -m "Update user-service image to ${GITHUB_SHA::7}-user"

      - name: Push changes
        run: |
          git push https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git main
