name: Build and Push Frontend Image, Update Kubernetes Manifests

on:
  repository_dispatch:
    types: [frontend_push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2
        with:
          repository: aitdevops/frontend
          token: ${{ secrets.GH_TOKEN }}
          path: frontend

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push frontend image
        run: |
          IMAGE_TAG=${{ github.event.client_payload.sha }}
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/frontend:$IMAGE_TAG -f frontend/frontend/Dockerfile ./frontend/frontend
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aitdevops-gke/frontend:$IMAGE_TAG

      - name: Configure git
        run: |
          git config --global user.email "rajeevkoppisetti21@gmail.com"
          git config --global user.name "aitdevops"

      - name: Clone argocd repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git
          cd argocd
          git checkout main

      - name: Update Kubernetes manifests
        run: |
          cd argocd
          IMAGE_TAG=${{ github.event.client_payload.sha }}
          sed -i 's|image: us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/frontend:.*|image: us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/frontend:'$IMAGE_TAG'|g' frontend/deployment.yaml
          git add frontend/deployment.yaml
          git commit -m "Update frontend image to $IMAGE_TAG"

      - name: Push changes
        run: |
          cd argocd
          git push https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git main
